version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: yapdilse
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pursoot_db
    ports:
      - "5432:5432"
    volumes:
      - ./pursoot-backend/init-scripts:/docker-entrypoint-initdb.d/
