version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: yapdilse
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pursoot_db
    ports:
      - "5432:5432"
    volumes:
      - ./pursoot-backend/init-scripts:/docker-entrypoint-initdb.d/

  api:
    build: ./pursoot-backend/api-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db

  models:
    build: ./pursoot-backend/models-python
    ports:
      - "5001:5000"
    depends_on:
      - db
